name: "cdnpurge"
on: push
jobs:
  purge-jsdelivr-cache:
    runs-on: ubuntu-20.04
    steps:
      - uses: gacts/purge-jsdelivr-cache@v1
        with:
          url: |
            https://cdn.jsdelivr.net/gh/ignaciocastro/adobe-is-dumb@latest/list.txt
            https://cdn.jsdelivr.net/gh/ignaciocastro/adobe-is-dumb@latest/127.txt
            https://cdn.jsdelivr.net/gh/ignaciocastro/adobe-is-dumb@latest/pihole.txt
